run_title: 'lama-fourier'

training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
losses:
  l1:
    weight_missing: 1
    weight_known: 1
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 0
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 0
  resnet_pl:
    weight: 0
    weights_path: ${env:TORCH_HOME}

defaults:
  - location: places
  - data: abl-04-256-mh-dist
  - generator: ffc_resnet_075
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: directory
  - evaluator: default_inpainted
  - trainer: any_gpu_large_ssim_ddp_final
  - hydra: overrides