# @package _group_
kind: ffc_resnet
input_nc: 3
output_nc: 3
ngf: 8
n_downsampling: 3
n_blocks: 9
add_out_act: sigmoid
use_mask_encoder: True
load_autoencoder: /home/engineer/Dev/igor/thesis/own/output_auto_lama_4(another_mask_encoder)/model.pth
freeze_autoencoder: true
use_latent_l2: true

init_conv_kwargs:
  ratio_gin: 0
  ratio_gout: 0
  enable_lfu: False

downsample_conv_kwargs:
  ratio_gin: ${generator.init_conv_kwargs.ratio_gout}
  ratio_gout: ${generator.downsample_conv_kwargs.ratio_gin}
  enable_lfu: False

resnet_conv_kwargs:
  ratio_gin: 0.75
  ratio_gout: ${generator.resnet_conv_kwargs.ratio_gin}
  enable_lfu: False
